/**
 * Default state profiles for DataQ challenge intelligence.
 *
 * Approval rates are conservative initial estimates.
 * The learning loop in stateProfileService will converge toward real data over time.
 */
module.exports = {
  'AL': { name: 'Alabama', approvalRate: 0.42, difficulty: 'moderate', avgDays: 45 },
  'AK': { name: 'Alaska', approvalRate: 0.48, difficulty: 'easy', avgDays: 35 },
  'AZ': { name: 'Arizona', approvalRate: 0.40, difficulty: 'moderate', avgDays: 50 },
  'AR': { name: 'Arkansas', approvalRate: 0.44, difficulty: 'moderate', avgDays: 40 },
  'CA': { name: 'California', approvalRate: 0.35, difficulty: 'hard', avgDays: 65 },
  'CO': { name: 'Colorado', approvalRate: 0.43, difficulty: 'moderate', avgDays: 45 },
  'CT': { name: 'Connecticut', approvalRate: 0.41, difficulty: 'moderate', avgDays: 50 },
  'DE': { name: 'Delaware', approvalRate: 0.45, difficulty: 'moderate', avgDays: 40 },
  'FL': { name: 'Florida', approvalRate: 0.38, difficulty: 'hard', avgDays: 55 },
  'GA': { name: 'Georgia', approvalRate: 0.39, difficulty: 'hard', avgDays: 55 },
  'HI': { name: 'Hawaii', approvalRate: 0.50, difficulty: 'easy', avgDays: 35 },
  'ID': { name: 'Idaho', approvalRate: 0.50, difficulty: 'easy', avgDays: 35 },
  'IL': { name: 'Illinois', approvalRate: 0.37, difficulty: 'hard', avgDays: 60 },
  'IN': { name: 'Indiana', approvalRate: 0.42, difficulty: 'moderate', avgDays: 45 },
  'IA': { name: 'Iowa', approvalRate: 0.46, difficulty: 'moderate', avgDays: 40 },
  'KS': { name: 'Kansas', approvalRate: 0.47, difficulty: 'moderate', avgDays: 40 },
  'KY': { name: 'Kentucky', approvalRate: 0.41, difficulty: 'moderate', avgDays: 45 },
  'LA': { name: 'Louisiana', approvalRate: 0.40, difficulty: 'moderate', avgDays: 50 },
  'ME': { name: 'Maine', approvalRate: 0.49, difficulty: 'easy', avgDays: 35 },
  'MD': { name: 'Maryland', approvalRate: 0.39, difficulty: 'hard', avgDays: 55 },
  'MA': { name: 'Massachusetts', approvalRate: 0.38, difficulty: 'hard', avgDays: 55 },
  'MI': { name: 'Michigan', approvalRate: 0.41, difficulty: 'moderate', avgDays: 50 },
  'MN': { name: 'Minnesota', approvalRate: 0.44, difficulty: 'moderate', avgDays: 45 },
  'MS': { name: 'Mississippi', approvalRate: 0.43, difficulty: 'moderate', avgDays: 45 },
  'MO': { name: 'Missouri', approvalRate: 0.42, difficulty: 'moderate', avgDays: 45 },
  'MT': { name: 'Montana', approvalRate: 0.52, difficulty: 'easy', avgDays: 30 },
  'NE': { name: 'Nebraska', approvalRate: 0.48, difficulty: 'easy', avgDays: 35 },
  'NV': { name: 'Nevada', approvalRate: 0.41, difficulty: 'moderate', avgDays: 50 },
  'NH': { name: 'New Hampshire', approvalRate: 0.49, difficulty: 'easy', avgDays: 35 },
  'NJ': { name: 'New Jersey', approvalRate: 0.36, difficulty: 'hard', avgDays: 60 },
  'NM': { name: 'New Mexico', approvalRate: 0.45, difficulty: 'moderate', avgDays: 40 },
  'NY': { name: 'New York', approvalRate: 0.35, difficulty: 'hard', avgDays: 65 },
  'NC': { name: 'North Carolina', approvalRate: 0.40, difficulty: 'moderate', avgDays: 50 },
  'ND': { name: 'North Dakota', approvalRate: 0.53, difficulty: 'easy', avgDays: 30 },
  'OH': { name: 'Ohio', approvalRate: 0.41, difficulty: 'moderate', avgDays: 50 },
  'OK': { name: 'Oklahoma', approvalRate: 0.44, difficulty: 'moderate', avgDays: 45 },
  'OR': { name: 'Oregon', approvalRate: 0.43, difficulty: 'moderate', avgDays: 45 },
  'PA': { name: 'Pennsylvania', approvalRate: 0.39, difficulty: 'hard', avgDays: 55 },
  'RI': { name: 'Rhode Island', approvalRate: 0.46, difficulty: 'moderate', avgDays: 40 },
  'SC': { name: 'South Carolina', approvalRate: 0.42, difficulty: 'moderate', avgDays: 45 },
  'SD': { name: 'South Dakota', approvalRate: 0.52, difficulty: 'easy', avgDays: 30 },
  'TN': { name: 'Tennessee', approvalRate: 0.41, difficulty: 'moderate', avgDays: 50 },
  'TX': { name: 'Texas', approvalRate: 0.38, difficulty: 'hard', avgDays: 60 },
  'UT': { name: 'Utah', approvalRate: 0.47, difficulty: 'moderate', avgDays: 40 },
  'VT': { name: 'Vermont', approvalRate: 0.51, difficulty: 'easy', avgDays: 30 },
  'VA': { name: 'Virginia', approvalRate: 0.40, difficulty: 'moderate', avgDays: 50 },
  'WA': { name: 'Washington', approvalRate: 0.42, difficulty: 'moderate', avgDays: 45 },
  'WV': { name: 'West Virginia', approvalRate: 0.46, difficulty: 'moderate', avgDays: 40 },
  'WI': { name: 'Wisconsin', approvalRate: 0.44, difficulty: 'moderate', avgDays: 45 },
  'WY': { name: 'Wyoming', approvalRate: 0.55, difficulty: 'easy', avgDays: 30 },
  'DC': { name: 'District of Columbia', approvalRate: 0.38, difficulty: 'hard', avgDays: 60 }
};
