const express = require('express');
const router = express.Router();
const { Driver, Vehicle, Violation, DrugAlcoholTest, Document, Accident, Company } = require('../models');
const { protect, checkPermission, restrictToCompany } = require('../middleware/auth');
const { asyncHandler, AppError } = require('../middleware/errorHandler');
const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');

router.use(protect);
router.use(restrictToCompany);

// Ensure reports directory exists
const reportsDir = path.join(process.cwd(), 'reports');
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

// Helper: Generate HTML for PDF
const generateReportHtml = (title, company, content, generatedBy) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { border-bottom: 2px solid #2c5282; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #2c5282; margin: 0; }
        .header .company { font-size: 18px; color: #666; margin-top: 5px; }
        .header .dot { font-size: 14px; color: #888; }
        .meta { font-size: 12px; color: #888; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .status-valid, .status-compliant { color: #28a745; }
        .status-warning, .status-due_soon { color: #ffc107; }
        .status-expired, .status-non_compliant, .status-critical { color: #dc3545; }
        .section { margin: 30px 0; }
        .section h2 { color: #2c5282; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        .summary-box { background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 11px; color: #888; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        <div class="company">${company.name}</div>
        <div class="dot">DOT# ${company.dotNumber}</div>
      </div>
      <div class="meta">
        Generated: ${new Date().toLocaleString()} | By: ${generatedBy}
      </div>
      ${content}
      <div class="footer">
        <p>This report was generated by VroomX Safety. For compliance purposes only.</p>
        <p>FMCSA regulations referenced: 49 CFR Parts 391, 396, 382</p>
      </div>
    </body>
    </html>
  `;
};

// @route   GET /api/reports/dqf
// @desc    Generate Driver Qualification File report
// @access  Private
router.get('/dqf', checkPermission('reports', 'view'), asyncHandler(async (req, res) => {
  const { driverId, format = 'json' } = req.query;
  const companyId = req.user.companyId._id || req.user.companyId;

  const query = { companyId, status: 'active' };
  if (driverId) query._id = driverId;

  const drivers = await Driver.find(query).select('-ssn');
  const company = await Company.findById(companyId);

  if (format === 'json') {
    return res.json({
      success: true,
      report: {
        type: 'Driver Qualification Files',
        generatedAt: new Date(),
        company: { name: company.name, dotNumber: company.dotNumber },
        drivers: drivers.map(d => ({
          name: `${d.firstName} ${d.lastName}`,
          employeeId: d.employeeId,
          cdl: {
            number: d.cdl?.number,
            state: d.cdl?.state,
            class: d.cdl?.class,
            expiry: d.cdl?.expiryDate,
            status: d.complianceStatus?.cdlStatus
          },
          medicalCard: {
            expiry: d.medicalCard?.expiryDate,
            status: d.complianceStatus?.medicalStatus
          },
          mvrStatus: d.complianceStatus?.mvrStatus,
          clearinghouseStatus: d.complianceStatus?.clearinghouseStatus,
          overallStatus: d.complianceStatus?.overall,
          documents: {
            employmentApplication: !!d.documents?.employmentApplication?.complete,
            roadTest: !!d.documents?.roadTest?.result,
            mvrReviews: d.documents?.mvrReviews?.length || 0
          }
        }))
      }
    });
  }

  // Generate PDF
  if (format === 'pdf') {
    const tableRows = drivers.map(d => `
      <tr>
        <td>${d.firstName} ${d.lastName}</td>
        <td>${d.employeeId}</td>
        <td class="status-${d.complianceStatus?.cdlStatus}">${d.cdl?.expiryDate ? new Date(d.cdl.expiryDate).toLocaleDateString() : 'N/A'}</td>
        <td class="status-${d.complianceStatus?.medicalStatus}">${d.medicalCard?.expiryDate ? new Date(d.medicalCard.expiryDate).toLocaleDateString() : 'N/A'}</td>
        <td class="status-${d.complianceStatus?.mvrStatus}">${d.complianceStatus?.mvrStatus || 'N/A'}</td>
        <td class="status-${d.complianceStatus?.overall}">${d.complianceStatus?.overall || 'N/A'}</td>
      </tr>
    `).join('');

    const content = `
      <div class="section">
        <h2>Driver Qualification Files Summary</h2>
        <table>
          <thead>
            <tr>
              <th>Driver Name</th>
              <th>Employee ID</th>
              <th>CDL Expiry</th>
              <th>Medical Expiry</th>
              <th>MVR Status</th>
              <th>Overall Status</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
      </div>
    `;

    const html = generateReportHtml('Driver Qualification Files Report', company, content, `${req.user.firstName} ${req.user.lastName}`);

    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    await browser.close();

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename=dqf-report-${Date.now()}.pdf`
    });
    return res.send(pdf);
  }
}));

// @route   GET /api/reports/vehicle-maintenance
// @desc    Generate Vehicle Maintenance report
// @access  Private
router.get('/vehicle-maintenance', checkPermission('reports', 'view'), asyncHandler(async (req, res) => {
  const { vehicleId, startDate, endDate, format = 'json' } = req.query;
  const companyId = req.user.companyId._id || req.user.companyId;

  const query = { companyId };
  if (vehicleId) query._id = vehicleId;

  const vehicles = await Vehicle.find(query);
  const company = await Company.findById(companyId);

  if (format === 'json') {
    return res.json({
      success: true,
      report: {
        type: 'Vehicle Maintenance',
        generatedAt: new Date(),
        company: { name: company.name, dotNumber: company.dotNumber },
        vehicles: vehicles.map(v => ({
          unitNumber: v.unitNumber,
          vin: v.vin,
          type: v.vehicleType,
          status: v.status,
          annualInspection: {
            lastDate: v.annualInspection?.lastInspectionDate,
            nextDue: v.annualInspection?.nextDueDate,
            status: v.complianceStatus?.inspectionStatus
          },
          maintenanceLog: v.maintenanceLog?.slice(-10) || []
        }))
      }
    });
  }

  // PDF generation
  if (format === 'pdf') {
    const vehicleContent = vehicles.map(v => `
      <div class="section">
        <h2>${v.unitNumber} - ${v.make || ''} ${v.model || ''}</h2>
        <div class="summary-box">
          <strong>VIN:</strong> ${v.vin} |
          <strong>Type:</strong> ${v.vehicleType} |
          <strong>Status:</strong> <span class="status-${v.status}">${v.status}</span>
        </div>
        <p><strong>Annual Inspection:</strong>
          Last: ${v.annualInspection?.lastInspectionDate ? new Date(v.annualInspection.lastInspectionDate).toLocaleDateString() : 'N/A'} |
          Next Due: ${v.annualInspection?.nextDueDate ? new Date(v.annualInspection.nextDueDate).toLocaleDateString() : 'N/A'}
        </p>
        <h3>Recent Maintenance</h3>
        <table>
          <thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Severity</th></tr></thead>
          <tbody>
            ${(v.maintenanceLog?.slice(-5) || []).map(m => `
              <tr>
                <td>${new Date(m.date).toLocaleDateString()}</td>
                <td>${m.maintenanceType}</td>
                <td>${m.description}</td>
                <td>${m.severity || 'N/A'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    `).join('');

    const html = generateReportHtml('Vehicle Maintenance Report', company, vehicleContent, `${req.user.firstName} ${req.user.lastName}`);

    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    await browser.close();

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename=maintenance-report-${Date.now()}.pdf`
    });
    return res.send(pdf);
  }
}));

// @route   GET /api/reports/violations
// @desc    Generate Violations report
// @access  Private
router.get('/violations', checkPermission('reports', 'view'), asyncHandler(async (req, res) => {
  const { startDate, endDate, format = 'json' } = req.query;
  const companyId = req.user.companyId._id || req.user.companyId;

  const query = { companyId };
  if (startDate || endDate) {
    query.violationDate = {};
    if (startDate) query.violationDate.$gte = new Date(startDate);
    if (endDate) query.violationDate.$lte = new Date(endDate);
  }

  const violations = await Violation.find(query)
    .populate('driverId', 'firstName lastName')
    .populate('vehicleId', 'unitNumber')
    .sort('-violationDate');

  const company = await Company.findById(companyId);

  if (format === 'json') {
    return res.json({
      success: true,
      report: {
        type: 'Violations Summary',
        generatedAt: new Date(),
        dateRange: { start: startDate, end: endDate },
        company: { name: company.name, dotNumber: company.dotNumber },
        summary: {
          total: violations.length,
          byBasic: violations.reduce((acc, v) => {
            acc[v.basic] = (acc[v.basic] || 0) + 1;
            return acc;
          }, {}),
          byStatus: violations.reduce((acc, v) => {
            acc[v.status] = (acc[v.status] || 0) + 1;
            return acc;
          }, {})
        },
        violations: violations.map(v => ({
          date: v.violationDate,
          type: v.violationType,
          basic: v.basic,
          severity: v.severityWeight,
          driver: v.driverId ? `${v.driverId.firstName} ${v.driverId.lastName}` : null,
          vehicle: v.vehicleId?.unitNumber,
          status: v.status,
          dataQ: v.dataQChallenge?.submitted ? v.dataQChallenge.status : null
        }))
      }
    });
  }

  // PDF format
  if (format === 'pdf') {
    const tableRows = violations.map(v => `
      <tr>
        <td>${new Date(v.violationDate).toLocaleDateString()}</td>
        <td>${v.violationType}</td>
        <td>${v.basic}</td>
        <td>${v.severityWeight}</td>
        <td>${v.driverId ? `${v.driverId.firstName} ${v.driverId.lastName}` : 'N/A'}</td>
        <td class="status-${v.status === 'resolved' || v.status === 'dismissed' ? 'valid' : 'warning'}">${v.status}</td>
      </tr>
    `).join('');

    const content = `
      <div class="section">
        <h2>Violations Summary</h2>
        <div class="summary-box">
          <strong>Total Violations:</strong> ${violations.length} |
          <strong>Date Range:</strong> ${startDate || 'All'} to ${endDate || 'Present'}
        </div>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>BASIC</th>
              <th>Severity</th>
              <th>Driver</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>
    `;

    const html = generateReportHtml('Violations Report', company, content, `${req.user.firstName} ${req.user.lastName}`);

    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    await browser.close();

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename=violations-report-${Date.now()}.pdf`
    });
    return res.send(pdf);
  }
}));

// @route   GET /api/reports/audit
// @desc    Generate full audit report
// @access  Private
router.get('/audit', checkPermission('reports', 'export'), asyncHandler(async (req, res) => {
  const { format = 'json' } = req.query;
  const companyId = req.user.companyId._id || req.user.companyId;

  const [company, drivers, vehicles, violations, drugTests, documents] = await Promise.all([
    Company.findById(companyId),
    Driver.find({ companyId, status: 'active' }),
    Vehicle.find({ companyId, status: { $in: ['active', 'maintenance'] } }),
    Violation.find({ companyId }).sort('-violationDate').limit(50),
    DrugAlcoholTest.find({ companyId }).sort('-testDate').limit(50),
    Document.find({ companyId, isDeleted: false })
  ]);

  const auditData = {
    type: 'Comprehensive Audit Report',
    generatedAt: new Date(),
    company: {
      name: company.name,
      dotNumber: company.dotNumber,
      mcNumber: company.mcNumber,
      smsBasics: company.smsBasics
    },
    driverQualification: {
      totalActive: drivers.length,
      compliant: drivers.filter(d => d.complianceStatus.overall === 'compliant').length,
      withIssues: drivers.filter(d => d.complianceStatus.overall !== 'compliant').length
    },
    vehicles: {
      total: vehicles.length,
      compliant: vehicles.filter(v => v.complianceStatus.overall === 'compliant').length,
      needingAttention: vehicles.filter(v => v.complianceStatus.overall !== 'compliant').length
    },
    violations: {
      total: violations.length,
      open: violations.filter(v => v.status === 'open').length,
      disputed: violations.filter(v => v.status === 'dispute_in_progress').length
    },
    drugAlcohol: {
      totalTests: drugTests.length,
      byType: drugTests.reduce((acc, t) => {
        acc[t.testType] = (acc[t.testType] || 0) + 1;
        return acc;
      }, {})
    },
    documents: {
      total: documents.length,
      expiringSoon: documents.filter(d => d.status === 'due_soon').length,
      expired: documents.filter(d => d.status === 'expired').length
    }
  };

  if (format === 'json') {
    return res.json({ success: true, report: auditData });
  }

  // Generate comprehensive PDF
  if (format === 'pdf') {
    const content = `
      <div class="section">
        <h2>Company Overview</h2>
        <div class="summary-box">
          <p><strong>Company:</strong> ${company.name}</p>
          <p><strong>DOT#:</strong> ${company.dotNumber}</p>
          <p><strong>MC#:</strong> ${company.mcNumber || 'N/A'}</p>
        </div>
      </div>

      <div class="section">
        <h2>SMS BASICs Summary</h2>
        <table>
          <tr><th>BASIC Category</th><th>Percentile</th><th>Status</th></tr>
          <tr><td>Unsafe Driving</td><td>${company.smsBasics?.unsafeDriving || 'N/A'}%</td><td>${company.smsBasics?.unsafeDriving >= 65 ? 'Alert' : 'OK'}</td></tr>
          <tr><td>HOS Compliance</td><td>${company.smsBasics?.hoursOfService || 'N/A'}%</td><td>${company.smsBasics?.hoursOfService >= 65 ? 'Alert' : 'OK'}</td></tr>
          <tr><td>Vehicle Maintenance</td><td>${company.smsBasics?.vehicleMaintenance || 'N/A'}%</td><td>${company.smsBasics?.vehicleMaintenance >= 80 ? 'Alert' : 'OK'}</td></tr>
          <tr><td>Controlled Substances</td><td>${company.smsBasics?.controlledSubstances || 'N/A'}%</td><td>${company.smsBasics?.controlledSubstances >= 80 ? 'Alert' : 'OK'}</td></tr>
          <tr><td>Driver Fitness</td><td>${company.smsBasics?.driverFitness || 'N/A'}%</td><td>${company.smsBasics?.driverFitness >= 80 ? 'Alert' : 'OK'}</td></tr>
          <tr><td>Crash Indicator</td><td>${company.smsBasics?.crashIndicator || 'N/A'}%</td><td>${company.smsBasics?.crashIndicator >= 65 ? 'Alert' : 'OK'}</td></tr>
        </table>
      </div>

      <div class="section">
        <h2>Driver Qualification Summary</h2>
        <div class="summary-box">
          <p><strong>Active Drivers:</strong> ${auditData.driverQualification.totalActive}</p>
          <p><strong>Compliant:</strong> <span class="status-compliant">${auditData.driverQualification.compliant}</span></p>
          <p><strong>With Issues:</strong> <span class="status-critical">${auditData.driverQualification.withIssues}</span></p>
        </div>
      </div>

      <div class="section">
        <h2>Vehicle Fleet Summary</h2>
        <div class="summary-box">
          <p><strong>Total Vehicles:</strong> ${auditData.vehicles.total}</p>
          <p><strong>Compliant:</strong> <span class="status-compliant">${auditData.vehicles.compliant}</span></p>
          <p><strong>Needing Attention:</strong> <span class="status-warning">${auditData.vehicles.needingAttention}</span></p>
        </div>
      </div>

      <div class="section">
        <h2>Violations Summary</h2>
        <div class="summary-box">
          <p><strong>Total Violations (Recent):</strong> ${auditData.violations.total}</p>
          <p><strong>Open:</strong> ${auditData.violations.open}</p>
          <p><strong>Under Dispute:</strong> ${auditData.violations.disputed}</p>
        </div>
      </div>

      <div class="section">
        <h2>Document Status</h2>
        <div class="summary-box">
          <p><strong>Total Documents:</strong> ${auditData.documents.total}</p>
          <p><strong>Expiring Soon:</strong> <span class="status-warning">${auditData.documents.expiringSoon}</span></p>
          <p><strong>Expired:</strong> <span class="status-critical">${auditData.documents.expired}</span></p>
        </div>
      </div>
    `;

    const html = generateReportHtml('Comprehensive Audit Report', company, content, `${req.user.firstName} ${req.user.lastName}`);

    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    await browser.close();

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename=audit-report-${Date.now()}.pdf`
    });
    return res.send(pdf);
  }
}));

module.exports = router;
